name: "Deploy Socotra Configuration"
description: "Deploy Socotra configuration to production or sandbox environments"
inputs:
  tenant-name:
    description: "Deployment target tenant name (eg. sigo-test, sigo-prod, or iarambula-uat)"
    required: true

  api-base:
    description: "API base used for all requests"
    required: true

  admin-username:
    description: "Admin username"
    required: true
  admin-password:
    description: "Admin password"
    required: true
  api-username:
    description: "API username"
    required: true
  api-password:
    description: "API password"
    required: true

  version:
    description: "Current configuration version"
    required: true
  config-path:
    description: "Socotra configuration path"
    required: true
outputs:
  hostname:
    description: "Hostname of deployment"
runs:
  using: "node12"
  main: "dist/index.js"
