name: 'Deploy Socotra Configuration'
description: 'Deploy Socotra configuration to production or sandbox environments'
inputs:
  username:
    description: 'Admin username'
    required: true
  password:
    description: 'Admin password'
    required: true
  auth-endpoint: 
    description: 'Endpoint used for admin authentication'
    required: true
  deploy-endpoint:
    description: 'Endpoint used for deployment'
    required: true    
  tenant-name:
    description: 'Deployment target tenant name (eg. sigo-test or sigo-prod)'
    required: true
outputs:
  hostname:
    description: 'Hostname of deployment'
runs:
  using: 'node12'
  main: 'dist/index.js'
